version: '3.5'
services:

#
# 实验版，请勿使用
#

  drone-server:
    image: drone/drone:${DRONE_VERSION}
    ports:
      - 8000:8000
    volumes:
      - drone-data:/var/lib/drone/
    restart: always
    environment:
      - DRONE_HOST=${DRONE_HOST_PRO}
      - DRONE_GITLAB=true
      - DRONE_GITLAB_CLIENT=fe548feb7819435d8f7c9236cf4ca30c
      - DRONE_GITLAB_SECRET=232a1ef9dd9148cbbf4034eb40f9736b
      - DRONE_GITLAB_URL=https://git.cloud.tencent.com
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:${DRONE_VERSION}
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}

volumes:
  drone-data:
